# Generated by Django 2.1.4 on 2018-12-21 10:04

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='desciption',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(default='/img/events/default/event_default.jpg', upload_to='img/events', verbose_name='Zdjęcie'),
        ),
    ]
