# Generated by Django 2.1.4 on 2018-12-21 11:24

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20181221_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(default='img/events/event_default.jpg', upload_to='img/events', verbose_name='Zdjęcie'),
        ),
    ]
