# Generated by Django 2.1.4 on 2019-06-11 16:09

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Nazwa zajęć')),
                ('description', models.TextField(max_length=2000, verbose_name='Opis zajęć')),
                ('order', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Kolejność wyświetlania')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji')),
            ],
            options={
                'verbose_name': 'Zajęcia',
                'verbose_name_plural': 'Zajęcia w ofercie',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Conditions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Tytuł')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Treść')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji')),
            ],
            options={
                'verbose_name': 'Regulamin',
                'verbose_name_plural': 'Regulamin',
            },
        ),
        migrations.CreateModel(
            name='PriceCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa cennika')),
                ('class_duration', models.PositiveSmallIntegerField(verbose_name='Czas trwania zajęć [min]')),
                ('items_in_row', models.CharField(choices=[('2', '2'), ('3', '3')], default='3', max_length=1, verbose_name='Liczba wyświetlanych kart w rzędzie')),
                ('order', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Kolejność wyświetlania')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji')),
            ],
            options={
                'verbose_name': 'Cennik - Kategoria',
                'verbose_name_plural': 'Cenniki - Kategorie',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PriceDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='Dodatkowe informacje')),
                ('order', models.PositiveSmallIntegerField(verbose_name='Kolejność wyświetlania')),
            ],
            options={
                'verbose_name': 'Karnet - szczegółowa informacja',
                'verbose_name_plural': 'Cenniki - Karnety - szczegółowe informacje',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PriceOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa karnetu')),
                ('price', models.PositiveSmallIntegerField(verbose_name='Cena')),
                ('order', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Kolejność wyświetlania')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji')),
                ('details', models.ManyToManyField(blank=True, related_name='get_price_option', to='classes.PriceDetail', verbose_name='Szczegóły')),
                ('price_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.PriceCategory', verbose_name='Nazwa Cennika')),
            ],
            options={
                'verbose_name': 'Cennik - Karnet',
                'verbose_name_plural': 'Cennki - Karnety',
                'ordering': ['order'],
            },
        ),
    ]
