# Generated by Django 2.1.4 on 2018-12-17 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Nazwa zajęć')),
                ('description', models.TextField(max_length=2000, verbose_name='Opis zajęć')),
                ('order', models.PositiveSmallIntegerField(verbose_name='Kolejność wyświetlania')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji')),
            ],
            options={
                'verbose_name': 'Zajęcia',
                'verbose_name_plural': 'Zajęcia w ofercie',
                'ordering': ['order'],
            },
        ),
    ]
