# Generated by Django 2.1.4 on 2019-07-08 19:51

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classoffer',
            options={'ordering': ['order'], 'verbose_name': 'zajęcia', 'verbose_name_plural': 'zajęcia w ofercie'},
        ),
        migrations.AlterModelOptions(
            name='conditions',
            options={'verbose_name': 'regulamin', 'verbose_name_plural': 'regulamin'},
        ),
        migrations.AlterModelOptions(
            name='pricecategory',
            options={'ordering': ['order'], 'verbose_name': 'cennik - kategoria', 'verbose_name_plural': 'cenniki - kategorie'},
        ),
        migrations.AlterModelOptions(
            name='pricedetail',
            options={'ordering': ['order'], 'verbose_name': 'karnet - szczegółowa informacja', 'verbose_name_plural': 'cenniki - karnety - szczegółowe informacje'},
        ),
        migrations.AlterModelOptions(
            name='priceoption',
            options={'ordering': ['order'], 'verbose_name': 'cennik - karnet', 'verbose_name_plural': 'cennki - karnety'},
        ),
        migrations.AlterField(
            model_name='classoffer',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='data utworzenia'),
        ),
        migrations.AlterField(
            model_name='classoffer',
            name='description',
            field=models.TextField(max_length=2000, verbose_name='opis zajęć'),
        ),
        migrations.AlterField(
            model_name='classoffer',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='kolejność wyświetlania'),
        ),
        migrations.AlterField(
            model_name='classoffer',
            name='title',
            field=models.CharField(max_length=100, verbose_name='nazwa zajęć'),
        ),
        migrations.AlterField(
            model_name='classoffer',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='data aktualizacji'),
        ),
        migrations.AlterField(
            model_name='conditions',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='treść'),
        ),
        migrations.AlterField(
            model_name='conditions',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='data utworzenia'),
        ),
        migrations.AlterField(
            model_name='conditions',
            name='title',
            field=models.CharField(max_length=100, verbose_name='tytuł'),
        ),
        migrations.AlterField(
            model_name='conditions',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='data aktualizacji'),
        ),
        migrations.AlterField(
            model_name='pricecategory',
            name='class_duration',
            field=models.PositiveSmallIntegerField(verbose_name='czas trwania zajęć [min]'),
        ),
        migrations.AlterField(
            model_name='pricecategory',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='data utworzenia'),
        ),
        migrations.AlterField(
            model_name='pricecategory',
            name='items_in_row',
            field=models.CharField(choices=[('2', '2'), ('3', '3')], default='3', max_length=1, verbose_name='liczba wyświetlanych kart w rzędzie'),
        ),
        migrations.AlterField(
            model_name='pricecategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='nazwa cennika'),
        ),
        migrations.AlterField(
            model_name='pricecategory',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='kolejność wyświetlania'),
        ),
        migrations.AlterField(
            model_name='pricecategory',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='data aktualizacji'),
        ),
        migrations.AlterField(
            model_name='pricedetail',
            name='description',
            field=models.CharField(max_length=100, verbose_name='dodatkowe informacje'),
        ),
        migrations.AlterField(
            model_name='pricedetail',
            name='order',
            field=models.PositiveSmallIntegerField(verbose_name='kolejność wyświetlania'),
        ),
        migrations.AlterField(
            model_name='priceoption',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='data utworzenia'),
        ),
        migrations.AlterField(
            model_name='priceoption',
            name='details',
            field=models.ManyToManyField(blank=True, related_name='get_price_option', to='classes.PriceDetail', verbose_name='szczegóły'),
        ),
        migrations.AlterField(
            model_name='priceoption',
            name='name',
            field=models.CharField(max_length=100, verbose_name='nazwa karnetu'),
        ),
        migrations.AlterField(
            model_name='priceoption',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='kolejność wyświetlania'),
        ),
        migrations.AlterField(
            model_name='priceoption',
            name='price',
            field=models.PositiveSmallIntegerField(verbose_name='cena'),
        ),
        migrations.AlterField(
            model_name='priceoption',
            name='price_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.PriceCategory', verbose_name='nazwa cennika'),
        ),
        migrations.AlterField(
            model_name='priceoption',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='data aktualizacji'),
        ),
    ]
