# Generated by Django 2.1.4 on 2018-12-19 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_conditions'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa cennika')),
                ('class_duration', models.PositiveSmallIntegerField(verbose_name='Czas trwania zajęć [min]')),
                ('items_in_row', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=1, verbose_name='Liczba wyświetlanych kart w rzędzie')),
                ('order', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Kolejność wyświetlania')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji')),
            ],
            options={
                'verbose_name': 'Cennik - Kategoria',
                'verbose_name_plural': 'Cenniki - Kategorie',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PriceDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='Dodatkowe informacje')),
                ('order', models.PositiveSmallIntegerField(verbose_name='Kolejność wyświetlania')),
            ],
            options={
                'verbose_name': 'Karnet - szczegółowa informacja',
                'verbose_name_plural': 'Karnety - szczegółowe informacje',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PriceOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa karnetu')),
                ('price', models.PositiveSmallIntegerField(verbose_name='Cena')),
                ('order', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Kolejność wyświetlania')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji')),
                ('details', models.ManyToManyField(to='classes.PriceDetails')),
                ('price_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.PriceCategory', verbose_name='Nazwa Cennika')),
            ],
            options={
                'verbose_name': 'Cennik - Karnet',
                'verbose_name_plural': 'Cennki - Karnety',
                'ordering': ['order'],
            },
        ),
    ]
