# Generated by Django 2.1.4 on 2018-12-19 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_pricecategory_pricedetails_priceoption'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PriceDetails',
            new_name='PriceDetail',
        ),
    ]
