# Generated by Django 2.1.4 on 2018-12-19 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_auto_20181219_1157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricedetail',
            options={'ordering': ['order'], 'verbose_name': 'Karnet - szczegółowa informacja', 'verbose_name_plural': 'Cenniki - Karnety - szczegółowe informacje'},
        ),
        migrations.AlterField(
            model_name='pricecategory',
            name='items_in_row',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], default='3', max_length=1, verbose_name='Liczba wyświetlanych kart w rzędzie'),
        ),
    ]
