# Generated by Django 2.1.4 on 2018-12-19 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0006_auto_20181219_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceoption',
            name='details',
            field=models.ManyToManyField(blank=True, to='classes.PriceDetail'),
        ),
    ]
