# Generated by Django 2.1.4 on 2018-12-19 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0007_auto_20181219_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceoption',
            name='details',
            field=models.ManyToManyField(blank=True, related_name='get_price_option', to='classes.PriceDetail', verbose_name='Szczegóły'),
        ),
    ]
