# Generated by Django 2.1.4 on 2018-12-19 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0008_auto_20181219_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricecategory',
            name='items_in_row',
            field=models.CharField(choices=[('2', '2'), ('3', '3')], default='3', max_length=1, verbose_name='Liczba wyświetlanych kart w rzędzie'),
        ),
    ]
