# Generated by Django 2.1.4 on 2018-12-29 20:12

import colorful.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0009_auto_20181219_1613'),
        ('about', '0005_auto_20181217_2110'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassInSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('1_Poniedziałek', 'Poniedziałek'), ('2_Wtorek', 'Wtorek'), ('3_Środa', 'Środa'), ('4_Czwartek', 'Czwartek'), ('5_Piątek', 'Piątek'), ('6_Sobota', 'Sobota'), ('7_Niedziela', 'Niedziela')], max_length=14, verbose_name='Dzień tygodnia')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji')),
            ],
            options={
                'verbose_name': 'Zajęcia w Grafiku',
                'verbose_name_plural': 'Zajęcia w Grafiku',
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='ClassType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nazwa zajęć')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji')),
                ('description', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='classes.ClassOffer', verbose_name='Opis zajęć')),
            ],
            options={
                'verbose_name': 'Rodzaj zajęć',
                'verbose_name_plural': 'Rodzaje zajęć',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('color', colorful.fields.RGBColorField(default='#007bff', verbose_name='Kolor')),
            ],
            options={
                'verbose_name': 'Kolor',
                'verbose_name_plural': 'Kolory',
            },
        ),
        migrations.CreateModel(
            name='StartTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(verbose_name='Godzina rozpoczęcia')),
            ],
            options={
                'verbose_name': 'Godzina rozpoczęcia zajęć',
                'verbose_name_plural': 'Godziny rozpoczęcia zajęć',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Imię i nazwisko instruktora')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji')),
                ('description', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='about.Teacher', verbose_name='Opis instruktora')),
            ],
            options={
                'verbose_name': 'Instruktor',
                'verbose_name_plural': 'Instruktorzy',
            },
        ),
        migrations.AddField(
            model_name='classtype',
            name='display_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.Color', verbose_name='Kolor wyświetlania'),
        ),
        migrations.AddField(
            model_name='classinschedule',
            name='class_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.ClassType', verbose_name='Nazwa zajęć'),
        ),
        migrations.AddField(
            model_name='classinschedule',
            name='start_time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.StartTime', verbose_name='Godzinya rozpoczęcia zajęć'),
        ),
        migrations.AddField(
            model_name='classinschedule',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Teacher', verbose_name='Instruktor'),
        ),
    ]
