# Generated by Django 2.1.4 on 2019-06-11 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classtype',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nazwa zajęć'),
        ),
    ]
