# Generated by Django 2.1.4 on 2018-12-29 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='starttime',
            old_name='start_time',
            new_name='time',
        ),
    ]
