# Generated by Django 2.1.4 on 2019-04-08 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20181229_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classinschedule',
            name='start_time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.StartTime', verbose_name='Godzina rozpoczęcia zajęć'),
        ),
    ]
