# Generated by Django 2.1.4 on 2018-12-17 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presentation', models.TextField(max_length=2000, verbose_name='Prezentacja')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji')),
            ],
            options={
                'verbose_name': 'O Nas',
                'verbose_name_plural': 'O Nas',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Imię i nazwisko')),
                ('description', models.TextField(max_length=2000, verbose_name='Opis')),
                ('order', models.IntegerField(blank=True, null=True, verbose_name='Kolejność')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji')),
            ],
            options={
                'verbose_name': 'Instruktor',
                'verbose_name_plural': 'Instruktorzy',
                'ordering': ['order'],
            },
        ),
    ]
