# Generated by Django 2.1.4 on 2018-12-17 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='picture',
            field=models.ImageField(default=1, upload_to='', verbose_name='Zdjęcie'),
            preserve_default=False,
        ),
    ]
