# Generated by Django 2.1.4 on 2018-12-17 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_auto_20181217_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutinfo',
            name='image',
            field=models.ImageField(upload_to='img/about/about_info', verbose_name='Zdjęcie'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=models.ImageField(upload_to='img/about/teacher', verbose_name='Zdjęcie'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Kolejność'),
        ),
    ]
